"""empty message

Revision ID: 824854d33c60
Revises: 39cfbab66ddf
Create Date: 2021-11-16 17:11:41.667828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824854d33c60'
down_revision = '39cfbab66ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('application_tags',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('app_id', 'tag_id')
    )
    op.create_index(op.f('ix_application_tags_app_id'), 'application_tags', ['app_id'], unique=False)
    op.create_index(op.f('ix_application_tags_tag_id'), 'application_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_tags_tag_id'), table_name='application_tags')
    op.drop_index(op.f('ix_application_tags_app_id'), table_name='application_tags')
    op.drop_table('application_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
