version: "3.5"

services:
  proxy:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 0.0.0.0:80:80

  backend:
    build: ./backend

  frontend:
    build: ./frontend
