version: "3.5"

services:
  web:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 127.0.0.1:9000:80

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ssgg_database:/database
    environment:
      SQLITE_DB: "/database/sqlite.db"
    command: "uvicorn web.app:app --host 0.0.0.0 --port 80 --reload"

  frontend:
    image: node:slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      PORT: 80
    command: "bash -c 'npm install; npm run start'"

volumes: 
  ssgg_database:
    external: true