version: "3.5"

services:
  web:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 127.0.0.1:80:80

  backend:
    build: ./backend

  frontend:
    build: ./frontend
