version: "3.5"

services:
  # Project services
  proxy:
    build: proxy
    depends_on:
      - frontend
      - backend-web
    ports:
      - "127.0.0.1:9000:80"

  backend-web:
    build:
      context: ./backend
      dockerfile: web/Dockerfile
    volumes:
      - ./backend/common:/app/common
      - ./backend/web:/app/main
      - ssgg_database:$DB_FOLDER
    environment:
      SQLITE_PATH: $STEAM_DB_PATH
    command: "uvicorn main.app:app --host 0.0.0.0 --port 80 --reload"

  steam-db-handler:
    &steam_db
    build:
      context: ./backend
      dockerfile: steam_db_handler/Dockerfile
    volumes:
      - ./backend/common:/app/common
      - ./backend/steam_db_handler:/app/main
      - ssgg_database:$DB_FOLDER
    environment:
      SQLITE_PATH: $STEAM_DB_PATH
    profiles:
      - disabled

  frontend:
    image: node:lts-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: "bash -c 'npm install; npm run dev'"

  # Helper services
  steam-db-revision:
    # Create a revision of steam database
    <<: *steam_db
    command: alembic -c common/steam_database/alembic/alembic.ini revision --autogenerate
    profiles:
      - disabled

  steam-db-reset:
    # Remove steam database
    <<: *steam_db
    command: rm $STEAM_DB_PATH
    profiles:
      - disabled

  frontend-prettify:
    # Prettify frontend code
    image: node:lts-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run prettify
    profiles:
      - disabled


volumes:
  ssgg_database:
    external: true
