version: "3.5"

services:
  proxy:
    image: ghcr.io/igorzamyslov/ssgg/proxy:master
    environment:
      VIRTUAL_HOST: ssgg.fun
      LETSENCRYPT_HOST: ssgg.fun
    depends_on:
      - frontend
      - backend-web
    networks:
      - proxy
      - ssgg

  backend-web:
    image: ghcr.io/igorzamyslov/ssgg/backend:master
    volumes:
      - ssgg_database:$DB_FOLDER
    environment:
      STEAM_DB_PATH: $STEAM_DB_PATH
      SSGG_DB_PATH: $SSGG_DB_PATH
    networks:
      - ssgg

  steam-db-handler:
    image: ghcr.io/igorzamyslov/ssgg/steam-db-handler:master
    volumes:
      - ssgg_database:$DB_FOLDER
    environment:
      STEAM_DB_PATH: $STEAM_DB_PATH
    networks:
      - default

  frontend:
    image: ghcr.io/igorzamyslov/ssgg/frontend:master
    networks:
      - ssgg

networks:
  ssgg:
    internal: true
  proxy:
    external: true

volumes:
  ssgg_database:
    external: true
