version: "3.5"

services:
  proxy:
    image: ghcr.io/igorzamyslov/ssgg/proxy:master
    environment:
      VIRTUAL_HOST: ssgg.fun
      LETSENCRYPT_HOST: ssgg.fun
    depends_on:
      - frontend
      - backend-web
    networks:
      - proxy
      - ssgg

  backend-web:
    image: ghcr.io/igorzamyslov/ssgg/backend:master
    depends_on:
      - backend-db-upgrade
    volumes:
      - ssgg_database:$DB_FOLDER
    environment:
      SQLITE_PATH: $DB_PATH
    networks:
      - ssgg

  backend-db-handler:
    image: ghcr.io/igorzamyslov/ssgg/db-handler:master
    depends_on:
      - backend-db-upgrade
    volumes:
      - ssgg_database:$DB_FOLDER
    environment:
      SQLITE_PATH: $DB_PATH
    networks:
      - default

  backend-db-upgrade:
    image: ghcr.io/igorzamyslov/ssgg/db-upgrader:master
    volumes:
      - ssgg_database:$DB_FOLDER
    environment:
      SQLITE_PATH: $DB_PATH

  frontend:
    image: ghcr.io/igorzamyslov/ssgg/frontend:master
    networks:
      - ssgg

networks:
  ssgg:
    internal: true
  proxy:
    external: true

volumes:
  ssgg_database:
    external: true
