version: "3.5"

services:
  proxy:
    image: nginx:alpine
    environment:
      VIRTUAL_HOST: ssgg.fun
      LETSENCRYPT_HOST: ssgg.fun
    depends_on:
      - frontend
      - backend-web
    volumes:
      - ./proxy.nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy
      - ssgg

  backend-web:
    build:
      context: ./backend
      dockerfile: web/Dockerfile
    depends_on:
      - backend-db-upgrade
    volumes:
      - ssgg_database:$DB_FOLDER
    environment:
      SQLITE_PATH: $DB_PATH
    networks:
      - ssgg

  backend-db-handler:
    build:
      context: ./backend
      dockerfile: database_handler/Dockerfile
    depends_on:
      - backend-db-upgrade
    volumes:
      - ssgg_database:$DB_FOLDER
    environment:
      SQLITE_PATH: $DB_PATH
    networks:
      - default

  backend-db-upgrade:
    build:
      context: ./backend
      dockerfile: database_migration/Dockerfile
    volumes:
      - ssgg_database:$DB_FOLDER
    environment:
      SQLITE_PATH: $DB_PATH

  frontend:
    build: ./frontend
    networks:
      - ssgg

networks:
  ssgg:
    internal: true
  proxy:
    external: true

volumes:
  ssgg_database:
    external: true
