version: "3.5"

services:
  proxy:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend-web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 0.0.0.0:80:80

  backend-web:
    build: 
      context: ./backend
      dockerfile: web/Dockerfile
    depends_on:
      - backend-db-upgrade
    volumes:
      - ssgg_database:$DB_FOLDER
    environment:
      SQLITE_PATH: $DB_PATH

  backend-db-handler:
    build: 
      context: ./backend
      dockerfile: database_handler/Dockerfile
    depends_on:
      - backend-db-upgrade
    volumes:
      - ssgg_database:$DB_FOLDER
    environment:
      SQLITE_PATH: $DB_PATH

  backend-db-upgrade:
    build:
      context: ./backend
      dockerfile: alembic/Dockerfile
    volumes:
      - ssgg_database:$DB_FOLDER
    environment:
      SQLITE_PATH: $DB_PATH

  frontend:
    build: ./frontend

volumes: 
  ssgg_database:
    external: true