"""empty message

Revision ID: a4363330d162
Revises: a4f39ff0b48c
Create Date: 2021-10-24 13:14:19.554602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4363330d162'
down_revision = 'a4f39ff0b48c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_screenshots_app_id'), 'screenshots', ['app_id'], unique=False)
    op.create_index(op.f('ix_screenshots_id'), 'screenshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenshots_id'), table_name='screenshots')
    op.drop_index(op.f('ix_screenshots_app_id'), table_name='screenshots')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    # ### end Alembic commands ###
