"""empty message

Revision ID: a8fb7b1b7413
Revises:
Create Date: 2021-10-25 11:30:57.080780

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a8fb7b1b7413'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developers_id'), 'developers', ['id'], unique=False)
    op.create_index(op.f('ix_developers_name'), 'developers', ['name'], unique=True)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishers_id'), 'publishers', ['id'], unique=False)
    op.create_index(op.f('ix_publishers_name'), 'publishers', ['name'], unique=True)
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_types_id'), 'types', ['id'], unique=False)
    op.create_index(op.f('ix_types_name'), 'types', ['name'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_type_id'), 'applications', ['type_id'], unique=False)
    op.create_table('_application_categories',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('app_id', 'category_id')
    )
    op.create_index(op.f('ix__application_categories_app_id'), '_application_categories', ['app_id'], unique=False)
    op.create_index(op.f('ix__application_categories_category_id'), '_application_categories', ['category_id'], unique=False)
    op.create_table('_application_developers',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('app_id', 'developer_id')
    )
    op.create_index(op.f('ix__application_developers_app_id'), '_application_developers', ['app_id'], unique=False)
    op.create_index(op.f('ix__application_developers_developer_id'), '_application_developers', ['developer_id'], unique=False)
    op.create_table('_application_genres',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('app_id', 'genre_id')
    )
    op.create_index(op.f('ix__application_genres_app_id'), '_application_genres', ['app_id'], unique=False)
    op.create_index(op.f('ix__application_genres_genre_id'), '_application_genres', ['genre_id'], unique=False)
    op.create_table('_application_publishers',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('app_id', 'publisher_id')
    )
    op.create_index(op.f('ix__application_publishers_app_id'), '_application_publishers', ['app_id'], unique=False)
    op.create_index(op.f('ix__application_publishers_publisher_id'), '_application_publishers', ['publisher_id'], unique=False)
    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshots_app_id'), 'screenshots', ['app_id'], unique=False)
    op.create_index(op.f('ix_screenshots_id'), 'screenshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenshots_id'), table_name='screenshots')
    op.drop_index(op.f('ix_screenshots_app_id'), table_name='screenshots')
    op.drop_table('screenshots')
    op.drop_index(op.f('ix__application_publishers_publisher_id'), table_name='_application_publishers')
    op.drop_index(op.f('ix__application_publishers_app_id'), table_name='_application_publishers')
    op.drop_table('_application_publishers')
    op.drop_index(op.f('ix__application_genres_genre_id'), table_name='_application_genres')
    op.drop_index(op.f('ix__application_genres_app_id'), table_name='_application_genres')
    op.drop_table('_application_genres')
    op.drop_index(op.f('ix__application_developers_developer_id'), table_name='_application_developers')
    op.drop_index(op.f('ix__application_developers_app_id'), table_name='_application_developers')
    op.drop_table('_application_developers')
    op.drop_index(op.f('ix__application_categories_category_id'), table_name='_application_categories')
    op.drop_index(op.f('ix__application_categories_app_id'), table_name='_application_categories')
    op.drop_table('_application_categories')
    op.drop_index(op.f('ix_applications_type_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_types_name'), table_name='types')
    op.drop_index(op.f('ix_types_id'), table_name='types')
    op.drop_table('types')
    op.drop_index(op.f('ix_publishers_name'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_id'), table_name='publishers')
    op.drop_table('publishers')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_developers_name'), table_name='developers')
    op.drop_index(op.f('ix_developers_id'), table_name='developers')
    op.drop_table('developers')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
